leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

ace_sys_spectator_can_exit_spectator = true;
ace_wounds_prevtime = 5;

// Teleport
onMapSingleClick {player setPos _pos};

private ["_i", "_j", "_c", "_pos_mk_spawnHunter", "_spawnHunter", "_mk_spawnAlien", "_pos_mk_spawnAlien"];

_spawnHunter = ["mk_spHunt1", "mk_spHunt2", "mk_spHunt3", "mk_spHunt4", "mk_spHunt5", "mk_spHunt6", "mk_spHunt7", "mk_spHunt8", "mk_spHunt9", "mk_spHunt10", "mk_spHunt11"];


//pas propre du tout
_i = floor(random(11) + 1);
_pos_mk_spawnHunter = getMarkerPos (_spawnHunter select _i);
_spawnHunter = _spawnHunter - [_spawnHunter select _i];
{
	_x setPosATL [(_pos_mk_spawnHunter select 0) + 1, _pos_mk_spawnHunter select 1, 0];
}forEach units grp1;

_i = floor(random(10) + 1);
_pos_mk_spawnHunter = getMarkerPos (_spawnHunter select _i);
_spawnHunter = _spawnHunter - [_spawnHunter select _i];
{
	_x setPosATL [(_pos_mk_spawnHunter select 0) + 1, _pos_mk_spawnHunter select 1, 0];
}forEach units grp2;

_i = floor(random(9) + 1);
_pos_mk_spawnHunter = getMarkerPos (_spawnHunter select _i);
_spawnHunter = _spawnHunter - [_spawnHunter select _i];
{
	_x setPosATL [(_pos_mk_spawnHunter select 0) + 1, _pos_mk_spawnHunter select 1, 0];
}forEach units grp3;

_i = floor(random(8) + 1);
_pos_mk_spawnHunter = getMarkerPos (_spawnHunter select _i);
_spawnHunter = _spawnHunter - [_spawnHunter select _i];
{
	_x setPosATL [(_pos_mk_spawnHunter select 0) + 1, _pos_mk_spawnHunter select 1, 0];
}forEach units grp4;

_i = floor(random(7) + 1);
_pos_mk_spawnHunter = getMarkerPos (_spawnHunter select _i);
_spawnHunter = _spawnHunter - [_spawnHunter select _i];
{
	_x setPosATL [(_pos_mk_spawnHunter select 0) + 1, _pos_mk_spawnHunter select 1, 0];
}forEach units grp5;

if(isServer or isDedicated) then
{
	_mk_spawnAlien = "mk_sp" + str(floor(random(11) + 1));
	_pos_mk_spawnAlien1 = getMarkerPos _mk_spawnAlien;
	alien1 setPosATL _pos_mk_spawnAlien1;
};


//fonction pour changer le joueur de camp une fois mort... to be continued
while {true} do
{
	if ((local player) && (!alive player) && (playerSide == east)) then
	{
		_pos_mk_spawnAlien = getMarkerPos("mk_sp" + str(floor(random(32) + 1)));
		_unit = groupAlien createUnit ["US_Delta_Force_SD_EP1", getPosATL alien1, [], 2, "NONE"];
		_unit setPosATL _pos_mk_spawnAlien;
		
		removeallweapons _unit;
		removeallitems _unit;
		removeBackpack _unit;

		[_unit,2,2,2,true] call ACE_fnc_PackIFAK;
		_unitplayerweap = [
			"SCAR_H_CQC_CCO_SD",
			"NVGoggles",
			"ItemCompass",
			"ItemGPS",
			"ItemMap",
			"ItemWatch"
		 ];

		_unitplayerammo = [
		  "20Rnd_762x51_SB_SCAR"
		 ];

		{_unit addmagazine _x} foreach _unitplayerammo;
		{_unit addWeapon _x} foreach _unitplayerweap;

		[_unit, ""] call ACE_fnc_PutWeaponOnBack;

		_unit selectWeapon (primaryWeapon _unit);
		setPlayable _unit;
		selectPlayer _unit;
	};
};
