leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

// Teleport
onMapSingleClick "player setPos _pos";

_spawnHunter = ["mk_spHunt1", "mk_spHunt2", "mk_spHunt3", "mk_spHunt4", "mk_spHunt5", "mk_spHunt6", "mk_spHunt7", "mk_spHunt8", "mk_spHunt9", "mk_spHunt10", "mk_spHunt11"];

{
	_j = 0; _c = 11; _i = 0;
	if(side player == east) then
	{
		_j = _i;
		_i = floor(random(11) + 1);
		while {(_j == _i) or (_i > _c)} do
		{
			_i = floor(random(11) + 1);
		};
		_pos_mk_spawnHunter = getMarkerPos (_spawnHunter select _i);
		_spawnHunter set [_i, objnull];
		sleep 0.1;
		ru_tl2 sideChat format["%1",_spawnHunter];
		sleep 0.1;
		_spawnHunter = _spawnHunter - [objnull];
		ru_tl2 sideChat format["%1",_spawnHunter];
		{
			_x setPosATL [(_pos_mk_spawnHunter select 0) + 1, _pos_mk_spawnHunter select 1, 0];
		} forEach units _x;
		_c = _c - 1;
	};
} forEach [grp1, grp2, grp3, grp4, grp5];

if(isServer or isDedicated) then
{
	_mk_spawnAlien = "mk_sp" + str(floor(random(11) + 1));
	_pos_mk_spawnAlien1 = getMarkerPos _mk_spawnAlien;
	alien1 setPosATL _pos_mk_spawnAlien1;
};

while {true} do
{
	if ((local player) && (!alive player) && (playerSide == east)) then
	{
		_pos_mk_spawnAlien = getMarkerPos("mk_sp" + str(floor(random(32) + 1)));
		_unit = groupAlien createUnit ["US_Delta_Force_SD_EP1", getPosATL alien1, [], 2, "NONE"];
		_unit setPosATL _pos_mk_spawnAlien;
		
		removeallweapons _unit;
		removeallitems _unit;
		removeBackpack _unit;

		[_unit,2,2,2,true] call ACE_fnc_PackIFAK;
		_unitplayerweap = [
		 "SCAR_H_CQC_CCO_SD",
		  "NVGoggles"
		 ];

		_unitplayerammo = [
		  "20Rnd_762x51_SB_SCAR"
		 ];

		{_unit addmagazine _x} foreach _unitplayerammo;
		{_unit addWeapon _x} foreach _unitplayerweap;

		[_unit, ""] call ACE_fnc_PutWeaponOnBack;

		_unit selectWeapon (primaryWeapon _unit);
		setPlayable _unit;
		selectPlayer _unit;
	};
};