/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.74
* Mon Mar 18 20:58:31 CET 2013
* Mission file name: test%20switch.Zargabad
* Mission name: test%20switch.Zargabad
* Required mods:
* + ACE
* 
* Call the script: _dummy = [] execvm "lea\loadout.sqf";
* 
*/

/**
* Loadout for vehicles
*/

//No named vehicles in this mission.

/**
* Loadout for ai units
*/

//No named AI units in this mission.

/**
* Loadout for playable units
*/

  removeallweapons alien1;
  removeallitems alien1;
  removeBackpack alien1;

  [alien1,2,2,2,true] call ACE_fnc_PackIFAK;
  _alien1playerweap = [
	 "SCAR_H_CQC_CCO_SD",
	 "NVGoggles",
	 "ItemCompass",
	 "ItemGPS",
	 "ItemMap",
	  "ItemWatch"
	 ];

  _alien1playerammo = [
	 "20Rnd_762x51_SB_SCAR",
	  "ACE_M84"
	 ];

  {alien1 addmagazine _x} foreach _alien1playerammo;
  {alien1 addWeapon _x} foreach _alien1playerweap;

  [alien1, ""] call ACE_fnc_PutWeaponOnBack;

  alien1 selectWeapon (primaryWeapon alien1);
