/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.74
* Init call for loadout scripts.
*/

enable_lea_addon = false;
ace_sys_wounds_no_medical_gear = true;

_dummy = [] execVM "lea\apply_loadout.sqf";

if (isServer && isMultiplayer) exitWith {
	_dummy = [] execVM "lea\loadout.sqf";
	waitUntil{scriptDone _dummy};
};

if (player != player) then {
	waitUntil {player == player};
};

waitUntil {local player};

if (!(player getVariable ["lea_already_connected", false])) then {
	while {!(player getVariable "lea_already_connected")} do {
	  sleep 1;
	};
	player setVariable ["lea_already_connected", true, true];
	_dummy = [] execVM "lea\loadout.sqf";
	waitUntil{scriptDone _dummy};
};